#pragma once

// Include GLM extension
#include <glm/gtc/matrix_transform.hpp>		// glm::translate, glm::rotate, glm::scale, ...
#include <glm/gtx/matrix_decompose.hpp>   // glm::decompose, ...
#include <glm/gtx/quaternion.hpp>					// glm::slerp, glm::toMat4, ...
