#pragma once

#include "Core/Core.hpp"
#include "Core/Log/Logger.hpp"
#include <entt/entt.hpp> 

/**
 * An entity is an identifier that represents an object in the game world.
 * It does not contain data per se, but acts as a "container" with wich components are associated.
 * The entity has no behaviour or state without components associated with it.
 * 
 * In Entt an entity is simply an ID generated by the register.
 */
class Entity
{
public:
	Entity()
		: _entity{ entt::null },
			_reg{ nullptr }
	{}

	Entity(entt::entity id, entt::registry* reg)
		: _entity{ id },
			_reg{ reg }
	{}

	template<typename T, typename...Args>
	T& AddComponent(Args&&... args)
	{
		if (GetComponent<T>())
			CONSOLE_WARN("Object already has component!");
		
		return _reg->emplace_or_replace<T>(_entity, std::forward<Args>(args)...);
	}

	template<typename T>
	T* GetComponent()
	{
		return _reg->try_get<T>(_entity);
	}

	template<typename T>
	void RemoveComponent()
	{
		if (!GetComponent<T>())
			CONSOLE_WARN("Object does not have component!");

		_reg->remove<T>(_entity);
	}

	constexpr entt::entity GetObjectID() const 
	{ 
		return _entity; 
	}

	void Invalidate()
	{
		_entity = entt::null;
		_reg = nullptr;
	}

	constexpr bool IsValid() const
	{
		return (_reg && _entity != entt::null);
	}

	bool IsEqual(const Entity& rhs) const
	{
		return static_cast<u32>(_entity) == static_cast<u32>(rhs.GetObjectID());
	}

private:
	entt::entity _entity;	/* The ID */
	entt::registry* _reg;	/* Pointer to the registry */
};
